name:     vk-api
version:  0.0.1
synopsis: Dealing with VKontakte API
category: API, VK, Web
author:   Aliaksei Valatouski

library:
  source-dirs: src
  other-modules:
    - Web.VK.Api.CommonTypes
    - Web.VK.Api.Param
  dependencies:
    - aeson
    - base
    - bytestring
    - http-client
    - http-client-tls
    - network-uri
    - random
    - split
    - text
  default-extensions:
    - BlockArguments
    - DeriveAnyClass
    - DerivingStrategies
    - DerivingVia
    - GeneralizedNewtypeDeriving
